---
- name: Configure Jenkins Server and EKS Access
  hosts: jenkins
  become: true
  
  roles:
    - role: jenkins
    - role: cloudwatch
    - role: eks-config 
    - role: sonarqube
    - role: sonar-scanner 